### ISSUE TITLE
onError SwitchChainNotSupportedError: "Rabby Wallet" does not support programmatic chain switching.

### ISSUE THREAD

**Issue by oxSaturn** [RabbyHub/Rabby#1986]
Does rabby wallet support programmatic chain switching?

When using `useSwitchChain` in wagmi v2 https://wagmi.sh/react/api/hooks/useSwitchChain#useswitchchain to switch chain automatically, it will throw the following error:

```
onError SwitchChainNotSupportedError: "Rabby Wallet" does not support programmatic chain switching.

Version: @wagmi/core@2.2.1
    at switchChain (switchChain.js:13:1)
    at Object.mutationFn (switchChain.js:8:31)
    at Object.fn (mutation.js:67:1)
    at run (retryer.js:83:1)
    at createRetryer (retryer.js:116:1)
    at executeMutation (mutation.js:62:36)
    at Mutation.execute (mutation.js:101:1)
```

Here's the code I used:

```
  const { switchChain } = useSwitchChain({
    mutation: {
      onSuccess() {
        console.log("onSuccess");
      },
      onMutate() {
        console.log("onMutate");
      },
      onError(e) {
        console.log("onError", e);
      }
    }
  });

//

switchChain({
          chainId: 250,
        });
```

Though it worked before with wagmi v1.

**Comment by oxSaturn** [comment]
hmm, probably I should ask this on rainbowkit as I'm using rainbowkit.
