### ISSUE TITLE
Unable to delete private key and contact address: No WalletConnect keyring found

### ISSUE THREAD

**Issue by mikoim** [RabbyHub/Rabby#2314]
- version: Rabby Wallet 0.92.74

## reproduction procedure
1. import private key or add contact address
2. try to delete the address from Manage Address
3. the following error occurs

```
{
    "message": "No WalletConnect keyring found",
    "stack": "Error: No WalletConnect keyring found\n    at r (chrome-extension://acmacodkjbdgmoleebolmdjonilkdbch/background.js:2:5680246)\n    at Object.internal (chrome-extension://acmacodkjbdgmoleebolmdjonilkdbch/background.js:2:5680853)\n    at te._getKeyringByType (chrome-extension://acmacodkjbdgmoleebolmdjonilkdbch/background.js:2:7730438)\n    at te.killWalletConnectConnector (chrome-extension://acmacodkjbdgmoleebolmdjonilkdbch/background.js:2:7707316)\n    at chrome-extension://acmacodkjbdgmoleebolmdjonilkdbch/background.js:2:7710067\n    at r.listenCallback (chrome-extension://acmacodkjbdgmoleebolmdjonilkdbch/background.js:2:7735379)\n    at r.onRequest (chrome-extension://acmacodkjbdgmoleebolmdjonilkdbch/background.js:2:11940338)\n    at chrome-extension://acmacodkjbdgmoleebolmdjonilkdbch/background.js:2:11941181",
    "code": -32603
}
```

**Comment by Admin686** [comment]
@mikoim you will have to use the Rabby loptimal weblink and try it again.

**Comment by vvvvvv1vvvvvv** [comment]
fixed in the latest version
