### ISSUE TITLE
Failed to check for transaction receipt

### ISSUE THREAD

**Issue by BenAzlay** [RabbyHub/Rabby#2662]
When executing a transaction, I am listening for the 'receipt' event, like:
```JS
tx.on("receipt", (receipt) => {
    // Success logic
});
```
With Rabby, this throws the following error:
```
Transaction error: Error: Failed to check for transaction receipt:
{}
    at Object._fireError (index.js:74:1)
    at index.js:243:1
```
When testing with Metamask, I am not encountering this issue. Also, when using a custom RPC url on Rabby, I am not encountering this issue.

This makes me think the problem lies with the default RPC url of Rabby. This is not an issue of exceeding the RPC capacity as I originally supposed, because even first-time users of the dApp have the issue.

**Comment by Athensmo** [comment]
It proceed successfully here... are you certain you are not experiencing glitch on your end?

**Comment by vvvvvv1vvvvvv** [comment]
what is your `tx.on("receipt"` actually do?

**Comment by BenAzlay** [comment]
The presence of `tx.on("receipt"` in the code is actually irrelevant to the issue. The error happens whether it is there or not.
